### ISSUE TITLE
how to create a report from resources

### ISSUE THREAD

**Issue by Yeleup** [laravel-json-api/non-eloquent#3]
For example

I have a loan resource and I need to create a report on them

Is it possible to implement it through a non-eloquent resource?

#start dat: '2023-01-01'
#end date: '2023-09-31'

#first line;
select count(*), sum(value) from loans where started_at <= '2023-01-01' and (closed_at is null or closed_at > '2023-01-01');

#for each period
select count(*), sum(value) from loans where started_at >= 'start-of-period' and started_at < ('end-of-period'); #count and value of STARTED loans
select count(*), sum(value) from loans where closed_at >= 'start-of-period' and closed_at < ('end-of-period'); #count and value of CLOSED loans

#last line
select count(*), sum(value) from loans where started_at <= '2023-09-31' and (closed_at is null or closed_at > '2023-09-31');

**Comment by lindyhopchris** [comment]
Hey! This non-Eloquent library is completely unoppionated about what you use it for - it just provides a way to "wire in" to the Laravel JSON:API implementation.

So yes, you could use it with the query builder to return whatever data you want. The only thing you'd need to consider is the encoder uses the class of the object it is encoding to the JSON:API format to work out how to encode it. So you wouldn't be able to just return rows from the database - you'd need to map them to a class that represents this data.

Hope that makes sense? Please close this issue if you don't have any follow-up questions.

**Comment by Yeleup** [comment]
Thanks for the answer

Can you help create a similar pesponse?

``` json
{
  "startData": {
    "count": 125,
    "value": 1001056.84
  },
  "endData": {
    "count": 163,
    "value": 1886604.11
  },
  lines: [
    {
      "period": "2023-01",
      "loansStarted": 44,
      "loansStartedValue": 228201.97,
      "loansClosed": 31,
      "loansClosedValue": 179153.48,
      "interestFees": 10700.18,
      "storageFees": 1370.60
      "executionFees": 2500.20
    },
    ...
  ]
  "linesSum": {
      "loansStarted": 432,
      "loansStartedValue": 4603472.51,
      "loansClosed": 394,
      "loansClosedValue": 3730925.24,
      "interestFees": 299315.25,
      "storageFees": 51509.27
      "executionFees": 60000.00
  }
}
```

**Comment by lindyhopchris** [comment]
So you'd need to take a look at the non-Eloquent docs and determine how to use it for your use case.

Having done the initial setup:
https://laraveljsonapi.io/docs/3.0/digging-deeper/non-eloquent.html#concept-initial-setup

For example, you'd need to decide whether that data is going to be returned by a query-all endpoint:
https://laraveljsonapi.io/docs/3.0/digging-deeper/non-eloquent.html#query-all-capability

Or a query-one:
https://laraveljsonapi.io/docs/3.0/digging-deeper/non-eloquent.html#read-capability

It's difficult for me to help out any further, because the whole concept of the non-Eloquent package is it allows you to do whatever you need to do, for your use case. Which is something I can't really determine!

**Comment by lindyhopchris** [comment]
Closing as information was provided.
